#!/usr/bin/env bash

# Create a directory for the output images
mkdir -p instagram_ready

# Loop through all images in the current directory
for img in *.jpg *.JPG; do
  # Get the dimensions of the image
  dimensions=$(identify -format "%wx%h" "$img")
  width=$(echo $dimensions | cut -d'x' -f1)
  height=$(echo $dimensions | cut -d'x' -f2)

  # Calculate padding to make the image square
  if [ "$width" -gt "$height" ]; then
    # Landscape
    new_height=$width
    padding_top=$((($width - $height) / 2))
    padding_bottom=$((($width - $height) - $padding_top))
    convert "$img" -gravity center -background white -extent ${width}x${width} "instagram_ready/$img"
  else
    # Portrait or square
    new_width=$height
    padding_left=$((($height - $width) / 2))
    padding_right=$((($height - $width) - $padding_left))
    convert "$img" -gravity center -background white -extent ${height}x${height} "instagram_ready/$img"
  fi
done

