;==========================================================
=======
include-file = ~/.config/polybar/colors.ini
[bar/main]
font-0 = "DejaVuSansM Nerd Font:size=12:weight=bold;6"
background = ${color.background}
foreground = ${color.foreground}

line-size = 2
line-color = ${color.primary}


border-bottom-size = 2
border-bottom-color = ${color.primary}


width = 100%:-50
offset-x = 25
offset-y = 10
height = 30

fixed-center = true
module-margin = 1
modules-left = menu i3
modules-center = 
modules-right = brightness pulseaudio battery tray powermenu
enable-ipc = true
override-redirect = true
wm-restack = i3


[module/brightness]
type = internal/backlight
card = intel_backlight

label = 󰃞 %percentage%%

[module/battery]
type = internal/battery
full-at = 99
battery = BAT0
adapter = ADP1
poll-interval = 5
time-format = %H:%M
ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 
format-charging = <ramp-capacity> <label-charging>
format-discharging = <ramp-capacity> <label-discharging>


[module/menu]
type = custom/menu
expand-right = true
menu-0-0 = Menu
menu-0-0-exec = ~/.config/polybar/docky/scripts/launcher.sh &
menu-0-1 = Files
menu-0-1-exec = thunar &
menu-0-2 = Terminal
menu-0-2-exec = termite &
menu-0-3 = Browser
menu-0-3-exec = firefox &

; Available tags:
;   <label-toggle> (default) - gets replaced with <label-(open|close)>
;   <menu> (default)
; Note that if you use <label-toggle> you must also include
; the definition for <label-open>

format = <label-toggle> <menu>
format-background = ${color.primary}
format-foreground = ${color.module-fg}
format-padding = 1

label-open = 
label-close = 

; Optional item separator
; Default: none
label-separator = " | "

[module/powermenu]
type = custom/menu

; If true, <label-toggle> will be to the left of the menu items (default).
; If false, it will be on the right of all the items.
#expand-right = true

; "menu-LEVEL-N" has the same properties as "label-NAME" with
; the additional "exec" property
>>>>>>> Stashed changes
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝

;==========================================================
; Importing files 
include-file = ~/.config/polybar/modules.ini
include-file = ~/.config/polybar/colors.ini

;==========================================================
[bar/i3_bar]
width = 100%
height = 18pt
radius = 0
dpi = 100
background = ${gruvbox.black}
foreground = ${gruvbox.cream}
border-size = 3pt
border-color = ${gruvbox.black}
module-margin = 0
padding-left=0pt
padding-right=0pt
separator ="."
separator-foreground = ${gruvbox.transparent}

font-0 = "Roboto condensed:size=11:weight=bold;2"
font-1 = "DejaVuSansM Nerd Font Mono:size=20:weight=bold;6"
font-2 = "DejaVuSansM Nerd Font Mono:size=12:weight=bold;6"

; Language Fonts

<<<<<<< Updated upstream
modules-left = rofi i3 
modules-right = tray cpu backlight memory pulseaudio battery time
cursor-click = pointer
;cursor-scroll = ns-resize
enable-ipc = true
wm-restack = i3
=======
label-open = 󰐥
label-close = 󰐥

; Optional item separator
; Default: none
label-separator = " | "

[module/i3]
type = internal/i3
enable-scroll = false
#pin-workspaces = true
strip-wsnumbers = true
index-sort = true
enable-click = true
fuzzy-match = true
show-urgent = true

; Available tokens:
;   %mode%
; Default: %mode%
label-mode = %mode%
label-mode-padding = 1
label-mode-background = #e60053

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-focused = %index%
label-focused-overline =  ${color.primary}
label-focused-foreground = ${color.primary}
label-focused-padding = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-unfocused = %index%
label-unfocused-padding = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-visible = %index%
label-visible-underline = #555555
label-visible-padding = 1

; Available tokens:
;   %name%
;   %icon%
;   %index%
;   %output%
; Default: %icon% %name%
label-urgent = %index%
label-urgent-foreground = #000000
label-urgent-background = #bd2c40
label-urgent-padding = 1

; Separator in between workspaces
label-separator =
label-separator-padding = 0
label-separator-foreground = #ffb52a

[module/tray]
type=internal/tray
format = <tray>
tray-spacing= 1px
format-padding= 1px %percentage%% 
format-background=${color.background}
tray-background = ${color.background}

[module/playerctl]
type = custom/script
exec = ~/.config/polybar/playerctl.sh
interval = 1

[module/pulseaudio]
label-volume = 󰕾 %percentage%%
label-muted = 󰝟 mut
type = internal/pulseaudio
>>>>>>> Stashed changes
