[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #201e1e
foreground = #e9e6d7
foreground-alt = #a3a196
alpha = #FF000000

;; shades
shade1 = #1b5e20
shade2 = #2e7d32
shade3 = #388e3c
shade4 = #43a047
shade5 = #4caf50
shade6 = #66bb6a
shade7 = #81c784
shade8 = #a5d6a7
